---
- name: Mitigate CVE-2024-6387 by setting LoginGraceTime 0
  hosts: all
  become: yes
  tasks:
    - name: Ensure the SSH configuration directory exists
      file:
        path: /etc/ssh
        state: directory

    - name: Backup the current sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.old-notmitigated
        remote_src: yes

    - name: Set LoginGraceTime to 0
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?LoginGraceTime\s*'
        line: 'LoginGraceTime 0'
        state: present

    - name: Ensure the SSH service is restarted on RedHat/Rocky Linux
      service:
        name: sshd
        state: restarted
      when: ansible_os_family in ['RedHat', 'Rocky']

    - name: Ensure the SSH service is restarted on Ubuntu
      service:
        name: ssh
        state: restarted
      when: ansible_os_family == 'Debian'

    - name: Verify that LoginGraceTime is set to 0
      command: grep '^LoginGraceTime 0' /etc/ssh/sshd_config
      register: verify_login_grace_time
      failed_when: verify_login_grace_time.rc != 0
      changed_when: false

    - name: Verify SSH service is running on RedHat/Rocky Linux
      shell: systemctl is-active sshd
      register: ssh_service_status_redhat
      failed_when: ssh_service_status_redhat.stdout.strip() != 'active'
      when: ansible_os_family in ['RedHat', 'Rocky']
      changed_when: false

    - name: Verify SSH service is running on Ubuntu
      shell: systemctl is-active ssh
      register: ssh_service_status_ubuntu
      failed_when: ssh_service_status_ubuntu.stdout.strip() != 'active'
      when: ansible_os_family == 'Debian'
      changed_when: false
